name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Falls dein Hauptbranch anders heißt, ändere es hier

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .  # Veröffentlicht den gesamten Repository-Inhalt

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
